# Setup
title:        Project or Site name
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      "http://www.shellgit.com"
paginate:     1

# About/contact
author:
  name:       琢玉
  url:        http://www.shellgit.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
